project:
  type: website
  output-dir: docs

website:
  title: "Nick McMillan"
  navbar:
    left:
      - index.qmd
      - project.qmd
      - blog.qmd
      - text: "Resume"
        href: resume.qmd
format:
  html:
    theme: litera
    css: styles.css



